{
    "tokenizer_model_path": "/data/aobuhtijarov/models/rubert_cased_L-12_H-768_A-12_pt",
    "enc_model_path": "/data/aobuhtijarov/models/pretrained_enc_8_layers",
    "dec_model_path": "/data/aobuhtijarov/models/pretrained_dec_6_layers",
    "max_tokens_text": 196,
    "max_tokens_title": 48,
    "gradient_accumulation_steps": 125,
    "batch_size": 4,
    "eval_steps": 400,
    "save_steps": 400,
    "logging_steps": 100,
    "learning_rate": 0.00005,
    "warmup_steps": 400,
    "num_train_epochs": 5,
}
